apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: pings
          persistentVolumeClaim:
            claimName: pings-pv-claim
      containers:
        - name: ping-pong
          image: ismomehdi/ping-pong:4
          volumeMounts:
          - name: pings
            mountPath: /usr/src/app/files
