apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-output
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: ping-pong
          image: ismomehdi/ping-pong:3
          volumeMounts:
          - name: shared-output
            mountPath: /usr/src/app/files
