apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: todo-app
          image: ismomehdi/todo-app:8
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/files
